version: '3.7'

services:
  www:
    build: ./
    restart: always
    environment:
      - TM_TRANSMISSION_URL=http://transmission:9091/transmission/rpc
    ports:
      - 80:80
    volumes:
      - ./data/downloads/:/root/www/files/
  transmission:
    build: ./transmission/
    restart: always
    volumes:
      - ./data/transmission/:/root/.config/transmission-daemon/
      - ./data/downloads/:/root/downloads/
      - ./data/downloads-partial/:/root/downloads-partial/
